FROM jenkins/jenkins:latest


ARG jenkins_url=http://localhost:8080
ARG admin_user=admin
ARG admin_pass=admin

ENV JENKINS_URL $jenkins_url
ENV JENKINS_USER $admin_user
ENV JENKINS_PASS $admin_pass
ENV JAVA_OPTS -Xmx1024m -Dhudson.footerURL=${JENKINS_URL}
ENV JENKINS_OPTS -Djenkins.install.runSetupWizard=false

RUN echo 2.0 > /usr/share/jenkins/ref/jenkins.install.UpgradeWizard.state
RUN echo 2.0 > /usr/share/jenkins/ref/jenkins.install.InstallUtil.lastExecVersion

COPY init.groovy/security.groovy /usr/share/jenkins/ref/init.groovy.d/
COPY init.groovy/theme.groovy /usr/share/jenkins/ref/init.groovy.d/

COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
